"""Unit tests for scripts/freeze_wireformat_snapshots.py (Story 1.21, AC7)."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

import freeze_wireformat_snapshots as fws
from sdlc.contracts import JournalEntry

pytestmark = pytest.mark.unit


def test_canonical_schema_bytes_deterministic() -> None:
    b1 = fws._canonical_schema_bytes(JournalEntry)
    b2 = fws._canonical_schema_bytes(JournalEntry)
    assert b1 == b2


def test_canonical_schema_bytes_is_utf8_ending_newline() -> None:
    b = fws._canonical_schema_bytes(JournalEntry)
    assert isinstance(b, bytes)
    assert b.endswith(b"\n")
    b.decode("utf-8")  # raises if not valid UTF-8


def test_canonical_schema_bytes_contains_schema_version() -> None:
    b = fws._canonical_schema_bytes(JournalEntry)
    assert b"schema_version" in b


def test_verify_one_returns_true_none_on_match(tmp_path: Path) -> None:
    path = tmp_path / "journal_entry.json"
    path.write_bytes(fws._canonical_schema_bytes(JournalEntry))
    ok, msg = fws._verify_one("journal_entry", JournalEntry, path)
    assert ok is True
    assert msg is None


def test_verify_one_returns_false_with_diff_on_mismatch(tmp_path: Path) -> None:
    path = tmp_path / "journal_entry.json"
    path.write_bytes(b'{"stale":"old_schema"}\n')
    ok, msg = fws._verify_one("journal_entry", JournalEntry, path)
    assert ok is False
    assert msg is not None
    assert "journal_entry" in msg


def test_write_one_creates_file_with_parents(tmp_path: Path) -> None:
    path = tmp_path / "v1" / "journal_entry.json"
    fws._write_one("journal_entry", JournalEntry, path)
    assert path.exists()
    content = json.loads(path.read_bytes())
    assert "schema_version" in str(content)


def test_main_check_exits_0_when_all_match() -> None:
    # Snapshots generated by Task 2 are present in the real repo tree.
    result = fws.main(["--check"])
    assert result == 0


def test_main_check_exits_1_when_snapshot_mutated(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    for slug, model_cls in fws._CONTRACTS:
        path = tmp_path / "tests" / "contract_snapshots" / "v1" / f"{slug}.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        if slug == "journal_entry":
            path.write_bytes(b'{"stale":"drift"}\n')
        else:
            path.write_bytes(fws._canonical_schema_bytes(model_cls))
    monkeypatch.setattr(fws, "_REPO_ROOT", tmp_path)
    result = fws.main(["--check"])
    assert result == 1


def test_main_check_exits_2_when_snapshot_missing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # No snapshot files in tmp_path — bootstrap failure expected.
    monkeypatch.setattr(fws, "_REPO_ROOT", tmp_path)
    result = fws.main(["--check"])
    assert result == 2


def test_main_write_regenerates_all_files(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(fws, "_REPO_ROOT", tmp_path)
    result = fws.main(["--write", "--yes"])
    assert result == 0
    for slug, model_cls in fws._CONTRACTS:
        path = tmp_path / "tests" / "contract_snapshots" / "v1" / f"{slug}.json"
        assert path.exists()
        assert path.read_bytes() == fws._canonical_schema_bytes(model_cls)


def test_main_write_yes_skips_prompt(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(fws, "_REPO_ROOT", tmp_path)
    prompt_called = [False]

    def _no_input(prompt: str) -> str:
        prompt_called[0] = True
        return "n"  # would abort if reached

    monkeypatch.setattr("builtins.input", _no_input)
    result = fws.main(["--write", "--yes"])
    assert result == 0
    assert prompt_called[0] is False
